flatpak/flatpak-builder-tools

pip/flatpak-pip-generator

i.e. name is at the top:
```
{
"name": "python3-cython",
"buildsystem": "simple",
"build-commands": [
"pip3 install --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} cython"
],
"sources": [
{
"type": "file",
"url": "https://pypi.python.org/packages/ee/2a/c4d2cdd19c84c32d978d18e9355d1ba9982a383de87d0fcb5928553d37f4/Cython-0.27.3.tar.gz",
"sha256": "6a00512de1f2e3ce66ba35c5420babaef1fe2d9c43a8faab4080b0dbcc26bc64"
}
]
}
```
rather than:
```
{
"buildsystem": "simple",
"sources": [
{
"url": "https://pypi.python.org/packages/ee/2a/c4d2cdd19c84c32d978d18e9355d1ba9982a383de87d0fcb5928553d37f4/Cython-0.27.3.tar.gz",
"sha256": "6a00512de1f2e3ce66ba35c5420babaef1fe2d9c43a8faab4080b0dbcc26bc64",
"type": "file"
}
],
"build-commands": [
"pip3 install --no-index …
```

pip generator: Generated json keys now follow a more natural order

---

npm/flatpak-npm-generator.py

Electron's 1.8 series has arm64 binaries. We should support this, since
Flathub can build them.

npm: Support Electron on arm64

---

pip/flatpak-pip-generator

This adds two more options to flatpak-pip-generator:
* A --cleanup option with the options of `all` or `scripts`. `all` deletes all files in the cleanup stage, `scripts` only deletes the contents of /bin. `--build-only` is now an alias for `--cleanup=all`.
* A `--output` option to explicitly specify an output file name.

Add some options for flatpak-pip-generator

---

pip/flatpak-pip-generator

After deleting the scripts, there's no point to keeping around any manpages that may have been installed for said scripts.

pip: also clean manpages when asked to clean up scripts

---

npm/flatpak-npm-generator.py

There was an inconsistency when switching to the 'domain' variable, as
some code still used the 'parsedUrl["domain"]' value which didn't exist
any longer. This made flatpak-npm-generator broken for some
package-lock.json files.

npm: Fix URL generation

---

npm/flatpak-npm-generator.py

Newer package-lock.jsons have a "from" key pointing to the original
repository. This needs to be deleted, or else npm will still try to go
to the network during the build.

npm: Remove "from" keys in package-lock.json

---

pip/flatpak-pip-generator

If you want to generate a manifest for diffoscope, including its
optional distro_detection and cmdline components. This invocation
correctly fetches the list of necessary packages:
flatpak-pip-generator 'diffoscope[distro_detection, cmdline]'
But in the resulting file, the 'build-commands' line is not properly
quoted, so 'diffoscope[distro_detection,' and 'cmdline]' are passed as
separate arguments to 'pip3 install', and the build fails.
Fix this by shell-quoting arguments using shlex.quote().
https://github.com/flathub/flathub/pull/698

pip: handle spaces in package names

---

npm/flatpak-npm-generator.py

Skip arm64 arch for electron < 1.8
See also:
https://github.com/flatpak/flatpak-builder-tools/issues/42
https://github.com/flatpak/flatpak-builder-tools/pull/43

flatpak-npm-generator.py: Fix for electron for arm64. Closes #42

---

poetry/flatpak-poetry-generator.py
poetry/readme.md

This new builder tool automatically creates a manifest based on the poetry.lock. Poetry has already done advanced dependency resolution, so this helps ensure that the versions of the packages used to build the Flatpak are consistent and repeatable to what Poetry is using.

Add Builder Tool for Python Poetry

---

node/.gitignore
node/README.md
node/flatpak-node-generator.py
node/mypy.ini
node/vanilla-quick-start/README.md
node/vanilla-quick-start/org.electronjs.ElectronQuickStart.yaml
node/webpack-quick-start/README.md
node/webpack-quick-start/build.electron.webpack.ElectronWebpackQuickStart.yaml
node/webpack-quick-start/generated-sources.json
npm/README.md
yarn/README.md

While working on a Scratch Flatpak, several problems with the current flatpak-npm-generator and flatpak-yarn-generator became readily apparent (I'll explain more below). So to work around this, I created flatpak-node-generator, which combines support for both npm and yarn in a much cleaner and more powerful generator script.
I haven't done any documentation or examples yet, that should be coming soon. I just figured I'd submit this here for early review.
flatpak-node-generator has many features and advantages over the other two scripts:
- Supports newer Node and npm versions. At some point during Node 10's release cycle, npm started *caching the registry http requests*, which is what started the initial rabbit hole into creating this new script. flatpak-npm-generator did not handle this. …

Add flatpak-node-generator

---

node/README.md
node/flatpak-node-generator.py

Missed this in the initial merge by a few hours :man_facepalming:, apparently a >100MB generated-sources.json is a normal thing in the npm world but isn't well-liked by GitHub, so I added a splitting mode, also documented some Chromedriver-related stuff.

Node extras

---

pip/flatpak-pip-generator

In my latest PR #59 that added requirements support, there was a regression caused by that which exported the module as a list.
Fixes #61

flatpak-pip-generator: fix regression caused by requirements support

---

pip/flatpak-pip-generator
poetry/flatpak-poetry-generator.py

This PR changes the pip builder tool to use the normal preferred pip download (wheel if available and sdist if there is no binary), and only force pip to use the sdist if pip downloads a platform specific wheel. 
In order to install an app using Poetry, I have to `pip install poetry`. Some of the Poetry dependencies like tomlkit require Poetry to build their sdist. So I get trapped in a catch-22, which can only be fixed by the FlatHub servers having Poetry (like setuptools), or we need to use the binary distributions that are available.
Use of a generic wheels should actually be preferred when they are available, since they offer:
- Faster installation for pure python packages
- Avoids arbitrary code execution for installation. (Avoids setup.py)
- Allows better caching for testing and …

PIP: Prefer Generic Wheels over sdist

---

cargo/flatpak-cargo-generator.py

This can happen when using dependency which are not from release crates,
like a specific git branch.
Fix #66

cargo: fix crash if checksum is not in metadata

---

poetry/flatpak-poetry-generator.py

Signed-off-by: Dan Yeaw <dan@yeaw.me>
Poetry allows optional dependencies to be defined. For example, you can define an optional group of dependencies in your `pyproject.toml` that are needed to build project docs.
The current behavior of the poetry builder tool is that it pulls in all optional dependencies.
Since optional dependencies shouldn't be needed to build an application, this PR excludes these dependencies.

Poetry: Remove optional dependencies from generated sources

---

poetry/flatpak-poetry-generator.py

Poetry upgraded the metadata in the lock files in poetry 1.0.0b2. This change supports the new metadata format, while keeping compatibility with the old format for users using an older version.

Support new poetry metadata format

---

flatpak-json2yaml.py

This prevents data loss.
I was accidentally executing the conversion script after I was nearly done. That caused my work to disappear. Sure, it's my fault, but I would have appreciated this safety net.

json2yaml: do not overwrite the yml file

---

pip/flatpak-pip-generator

When downloading a platform generic package, we need to make sure that we download the correct package version (when specified in the requirements file).
The `get_package_name()` function returns only the package name. Downloading a package only by its name results in downloading the latest version (which would create a conflict).

pip: fix incorrect package version when downloading platform generic packages

---

pip/readme.md

On IRC, after reading this documentation, someone asked for a
“requirements.txt file example?”, not realising this just refers to the
de-facto standard used by many Python projects. Add a link to clarify
this.

pip: add link to requirements.txt documentation

---

node/README.md
node/flatpak-node-generator.py
node/webpack-quick-start/build.electron.webpack.ElectronWebpackQuickStart.yaml
node/webpack-quick-start/generated-sources.json

This adds the following features:
- Ability to use ChromeDriver binaries from an Electron release for non-x64 architectures.
- Automated handling of the architecture-specific parameters to pass to electron-builder for non-x64.
- Ability to use non-patent-encumbered ffmpeg binaries.
- Use of a well-defined ordering for modules to try to avoid giant diffs on minor changes.

A lot of node generator improvements

---

go-get/flatpak-go-get-generator.py

This PR has two commits: One for making the code compatible with Python < 3.7 and the other for detecting dependencies more properly.  I don't know how "go get" behaves, so I have no clue what the correct fix here is, but it seems to make it work a little better than before. It's confident that it's not worse than before.
CCing @cagatay-y

go: detect git directory for dependencies

---

go-get/flatpak-go-vendor-generator.py

The existing tool does not work with syncthing. If only because you
cannot get hold of syncthing with "go get".
CC @cagatay-y

go: Added a script to read vendorised go dependencies

---

pip/flatpak-pip-generator

When I needed to use python2-pip in the guest, it refused to use wheels,
because --install-option is used. The Internet suggests, that --prefix
can be used, regardless.
It works for me™.
https://github.com/flatpak/flatpak-builder-tools/commit/74ccb11d19d6fd55bf530063dcec6833a5fb5ef3 seems to have introduced the `--install-options` flag which refers to an old pip version found in the 1.6 SDK. These times are probably over.
CCing @danyeaw as a recent committer of this file and @barthalion as the author of the commit mentioned above.

pip: use --prefix also for python2 pip

---

cargo/flatpak-cargo-generator.py

Hm. It's unfortunate that we make this change, but it seems to work much
better on gst-plugin-cdt.
The upstream cargo command explicitly checks for the presence of
"github.com" in the URL to then replace the protocol with "https".
We now additionally replace "git+https://" with "https://".
Initially, I tried to only replace when writing out the flatpak
manifest. But then I noticed how "cargo vendor" prints out the
"https://" URL (when telling you how to configure your cargo,
rather than "git+https", so something seems to have replaced the
prefix there.
We try to do the same.
Another change is the cloning of the bare repository into "git/db".
It seems cargo somehow and sometimes expects repositories to be there.
A "strace -e statx  cargo build" helped to reveal that it was looking for the …

cargo: centrally replace git+ urls and bare clone in to git/db

---

cargo/flatpak-cargo-generator.py

Fix `flatpak-cargo-generator.py` canoniclizing URLs ending in ".git".
E.g. trying `flatpak-cargo-generator.py` on the `Cargo.lock` from https://github.com/ImageOptim/gifski/ failed without this patch.

flatpak-cargo-generator: Fixed handling of URLs ending with .git

---

cpan/flatpak-cpan-generator.pl

The @ sign is meant literally here, so escape it.
In the original form the code will end with a fairly obscure error message
```
Not an ARRAY reference at ./flatpak-cpan-generator.pl line 77.
```
With the fix, the error message is printed as intended. Below for example is the error when printed when trying to generate flatpak cpan rules for Date::Parse:
```
Unexpected 0 releases for Date::Parse@2.31 at ./flatpak-cpan-generator.pl line 81.
```
Note: the reason the script fails on this module is because there is something odd going one with the `Date::Parse` module in cpan. If you try to install it, it will install the `TimeDate` module instead. I haven't figured out why yet or how the flatpak-cpan-generator script can be adjusted to deal with it.
This PR at least clarifies the error …

Fix unintended ARRAY reference error

---

cpan/README.md
cpan/flatpak-cpan-generator.pl

I have been experimenting with the cpan sources generator for the GnuCash flatpak. GnuCash can optionally use the `Finance::Quote` perl module so it would be nice to be able to ship it in the flatpak as well.
I ran into several issues while using the script:
1. Some modules have failing unit tests, causing the generation script to end prematurely. I currently seeing this with `HTML::TableExtract-2.15`
2. Some of the modules installed with `cpanm` failed to appear in the list of sources. I found two possible causes:
1. The particular module doesn't write anything to `perllocal.pod`. This is the case for example with `HTML::Tree`. These missing modules go unnoticed until the final flatpak tries to use them.
1. The module name written to `perllocal.pod` can't be mapped back to the module's …

Proposed improvements to the cpan sources generator

---

node/flatpak-node-generator.py

The generator produced wrongly looking URLs for git+https:// URLs:
Initialized empty Git repository in
/srv/buildbot/sources/git/https_github.com_Simon-Laux_parcel-plugin-clean-dist.git-JT0KG0/
fatal: unable to access
'https:////github.com/Simon-Laux/parcel-plugin-clean-dist.git/': Could
not resolve host: https; Unknown error
Failed to download sources: module delta: Child process exited with code
128
Notice how there are too many slashes.
Do also note how the behaviour should change now. The code suggests that
a URL starting with "git+https:" is going to be replaced with
"https://". This change changes this behaviour and strips the slashes
from the replacement. I hope that doesn't break any other users.
https://flathub.org/builds/#/builders/27/builds/15301
This could fix …

node: make it work with git+https urls

---

dub/flatpak-dub-generator.py

DUB is the package manager for D lang. This generator should supplement recently added to Flathub `ldc` and `dmd` SDK extensions.
I've never used  DUB before, so maybe did something sub-optimal here.
Adding `generated-sources.json` to the manifest should be enough for this to work.
CC @Cogitri

Add DUB generator

---

node/README.md
node/flatpak-node-generator.py

Some apps require electron-ffmpeg archive to be present alongside electron archive, so that cache layout would look like this:
```
flatpak-node/electron-cache
├── electron-v4.2.12-linux-x64.zip
├── ffmpeg-v4.2.12-linux-x64.zip
└── SHASUMS256.txt-4.2.12
```
This removes `--electron-non-patented-ffmpeg` option and adds `--electron-ffmpeg=` option with two possible values - `lib` and `archive`. The former will do the same that `--electron-non-patented-ffmpeg` currently does, while the later will instead add a file source with ffmpeg archive and place it alongside electron.

node: Option to download ffmpeg archive

---

cargo/flatpak-cargo-generator.py

- Put git source extraction to separate function
- Support for (new?) `Cargo.lock` format without `[[metadata]]`, but with `checksum` key per-package
- No need for `cargo vendor` to generate `.cargo-checksum.json` for git packages, create stub one ourselves
Tested on [ytop](https://github.com/cjbassi/ytop) (has git sources) and [kibi](https://github.com/ilai-deutel/kibi) (lockfile without metadata, no git).
Should fix #99

cargo: Partial rewrite

---

cargo/flatpak-cargo-generator.py

Kind of follow-up for #107 
In order to properly support git repos with workspace instead of single package, we need to parse `Cargo.toml`'s in there to determine what packages they contain.
Doing so, we don't need cached git repos (`cargo/git/db`) at all, so all related stuff can be removed, including siphash module.
This is tested on [Veloren](https://gitlab.com/veloren/veloren).
Possible improvements:

cargo: Properly support git repos with workspaces

---

cargo/flatpak-cargo-generator.py

Follow-up for #108 
It appears that `Cargo.toml` in git repo can contain both a `package` _and_ `workspace`.

cargo: Small fix for git packages support

---

pip/flatpak-pip-generator

This change adds the ability for developers to provide VCS type packages
to `flatpak-pip-generator`.
> flatpak-pip-generator "git+https://github.com/user/repo#egg=name"
The changes will parse the VSC package name and ensure it is handed
throughout the rest of the process. The reason for this change is to
allow developers to build a flatpak using packages that may not, nor
ever be, on PyPi.
Signed-off-by: Kevin Carter <kecarter@redhat.com>

Add the ability to use VSC packages

---

node/.style.yapf
node/README.md
node/flatpak-node-generator.py

This has been cooking for quite some time now and has some big new features:
- Package metadata is now trimmed to remove all data except for the versions that are used. This results in *massive* size reductions in the generated sources files: for Scratch, it shrank from ~170MB to around ~8MB, or **a 95% size reduction**. Idea was originally from @TingPing.
- Many requests are now cached on disk. For the Scratch Flatpak, generating the sources with a filled cache reduced the runtime from around 2 minutes and 27 seconds to just 41 seconds, which is **a 72% reduction in time**. @muelli please try it and give feedback.
Bug fixes:
- node-chromedriver works now, @Arxcis @x80486 please try. Note that upstream `@electron/get` no longer supports ELECTRON_CACHE, so I was originally working on a …

Many, many node improvements

---

dub/flatpak-dub-generator.py

This makes the dub sources generator almost 10 times faster, e.g. reducing generation time for backgammon app from ~30 seconds to 3-5 seconds.
@Cogitri is it ok to add hard dependency on an external python module (`aiohttp`)?

dub: Make http requests asynchronously

---

node/flatpak-node-generator.py

This adds missing bits for building VSCode:
- Correctly process multiple checksums in one integrity field of lockfile
- Handle `playwright` special source
- Create electron cache symlink for `gulp-atom-electron` package

node: More support for VSCode

---

node/flatpak-node-generator.py

Some modern versions of node-related tools start to conform XDG basedir spec to store/read their cache (i.e. respect `XDG_CACHE_HOME` env var). If all npm packages are such for given app, building this app can be made easier if put caches to exactly where packages will look for them, relative to `XDG_CACHE_HOME`.
This introduces `--xdg-layout` option that will put
- electron to `flatpak-node/cache/electron/electron-...zip` (instead of `flatpak-node/electron-cache`) 
- node-headers to `flatpak-node/cache/node-gyp/$version` (instead of `flatpak-node/node-gyp/electron-current`). 
Then, in flatpak-builder manifest, `XDG_CACHE_HOME` can be set to `/run/build/module_name/cache`. Other vars, such as `npm_config_nodedir` and `electron_config_cache` are not needed.
This is required to support …

node: Support for XDG basedir spec cache layout

---

pip/flatpak-pip-generator
pip/readme.md

* Fixes #102
* Correctly names modules, e.g. occurrences of `"name": "python3-foo>"`
* If foo.txt is supplied output is named python3-foo.json
* For multiple modules output is named python3-modules.json
* Added instructions for multiple packages with versions in readme
* Tells the user the name of the output json file
* CVS generates a "git" type source, but won't build

Use requirement parser

---

pip/flatpak-pip-generator

Tested with
```sh
git+git://github.com/psf/requests.git@c7e0fc087ceeadb8b4c84a0953a422c474093d6#egg=requests
certifi
```
produces a `json` file which is correctly builded with `flatpak-builder`. I am not convinced by the variable `name_for_pip` name.

pip: Fixes pip3 install command for vcs packages and extras

---

pip/flatpak-pip-generator

It was only fetching by package name instead of package[extra1,extra2], this together with #135
allow to get correctly generate manifests. Tested with the following requirements.txt
``` sh
Cython # Other comment, and whitespace
qdarkstyle==2.8
pyaes>=0.1a1
git+git://github.com/psf/requests.git@c7e0fc087ceeadb8b4c84a0953a422c474093d6#egg=requests
aiorpcx>=0.18,<0.19
requests[security,socks]>=2.8.1
```
It was also tested without the first apperance of `requests`. It is tempting to use the same variable for fetching `name_for_pip= name + extras + version` and installing `pkg= name + extras`, but the later breaks `flatpak-builder` when versions are added.

pip: Correctly fetches sources with extras

---

pip/flatpak-pip-generator

DONE: ~~Find a way to list the sources files only once.~~
with this PR the ALL sources will be listed once for each package. One possibility is to, instead of doing one module per package, do a single module with all packages. This would drastically decrease the length of the output file, even compared with `flatpak-pip-generator` before this PR, but we lose the ability to take off from the last built module in `flatpak-builder`.

pip: Refactor how sources are generated 

---

pip/flatpak-pip-generator

This pr eliminates the need to run `pip` with the `--no-binary` flag, this causes a great speedup in the process and greately reduces the ammount of data to download. Files which are arch dependent are redownloaded using the info in pypi.org. Solves #47, #131, #89, and #26. But doesn't address the fact that some `tar.gz` packages can't be just installed with `pip install`, such as `pyqt5`.
Bonus: The output was prettified significantly and a warning message will be show if the python version used is not the same as of org.freedesktop.Platform, packages as `qdarkstyle` would be downloaded specifically for the host python version.
**Whats left to do in a future PR:**
* Add a `--only-host-arch` flag to allow the use of, for example `*x86_64.whl` packages, this would fix most of all remaining …

pip: Eliminate calls of `pip download --no-binary`

---

pip/flatpak-pip-generator

The import of requirements-parser was moved,
requirements is used regardless of opts.requirements making it a hard dependency.

pip: Fix #142

---

node/flatpak-node-generator.py

`@electron/get` is the new electron binary downloader, official replacement for `electron-download` package.
It doesn't support env vars that set path to electron downloads cache, and stores downloads in a subdirectory with name based on full download url.

node: Create symlinks to zips for electron-get

---

cargo/flatpak-cargo-generator.py

The Python documentation states that "text" is a more readable alias for
"universinal_newlines". It was introduced with Python 3.7.
Ubuntu 18.04, however, run Python 3.6, is still supported, and doesn't
have an upgrade path yet.
This change brings compatibility with said Ubuntu version, but will
also benefit other Python 3.6 users.

cargo: maintain compatibility with Python 3.6

---

pip/flatpak-pip-generator

* For Python 3 packages it will run in the first runtime or sdk that it is available, running without a sandbox is not an option.
* Python 2 packages will use the host's `pip2` command unless a flatpak which bundles pip2 is specified. The is no natural choice flatpak the user should use as a default.
* The temporal requirements file is deleted as soon as it is not needed anymore.

pip: Run inside of a sandbox

---

node/flatpak-node-generator.py

Yarn mirrors git packages as uncompressed tarballs named after the  source repo and commit hash. I'm not quite sure if it's always the case, but it seems to be so for at least 1.22+

node: Support for Yarn git packages

---

cargo/flatpak-cargo-generator.py

Cargo.lock can reference a git package version by tag, we should support this.

cargo: Support tags in git packages

---

node/flatpak-node-generator.py

It appears that #144 broke git dependencies for npm by passing url with fragment to flatpak-builder.
fb2a0a7 restores previous behavior by removing the fragment from url.
Should fix #152

node: Fix git source url for npm

---

node/flatpak-node-generator.py

This change allows empty dependency declarations such as the one found
here: https://github.com/laurent22/joplin/blob/20bec7e26c175bc3fcd43be4c1a6c016c14a5fc8/Clipper/package.json
Passing the empty list should be semantically equivalent to no
dependencies.
It's probably not very common that a module doesn't have any dependencies... But I do wonder whether I am the first person to encounter empty dependencies.

node: handle empty dependencies

---

node/flatpak-node-generator.py

And stop relying on the ones generated by a git hosting provider.
Reason is that at least Github generates tarball with a root directory in the form of repo_name-commit_id/ which gets decompressed as is in node_modules by Yarn.
It is incompatible with webpack's resolver that expects a flat directory structure in node_modules.

[node] Generate our own tarball

---

cpan/flatpak-cpan-generator.pl

Enable the canonical format for the JSON encoder. This avoids
unnecessary differences when committing the generated file in, e.g.,
git. Unfortunately the output is not completely deterministic as the
output from cpanm may vary.

cpan: Make the output more deterministic

---

pip/flatpak-pip-generator

Also support more tarball types

pip: always build from source tarball (discarding wheel file)

---

pip/flatpak-pip-generator

From my own test, pip is not sensible to case when installing a package from a requirements.txt file
Also update list of system packages in `org.freedesktop.Sdk//20.08`

pip: make system_packages search case insensitive

---

pip/flatpak-pip-generator

It's a boolean and does not expect a value

pip: fix --no-build-isolation option parsing

---

pip/flatpak-pip-generator

pip doesn't seem to make a difference betweek `-` and `_`
For example for flake8-bugbear, the source package name is flake8_bugbear, which causes it to be skipped when constructing the source map
but you also have setuptools_scm, for which the source name is the same as the package name.

pip: fix some edge cases in dependency to source mapping

---

cargo/flatpak-cargo-generator.py

This adds an option to download git-based crates as tarballs for known git hosts.
Adds `aiohttp` dependency.

cargo: Partial rewrite and more http usage

---

node/flatpak-node-generator.py

electron/get starting from 1.12.4 uses url checksum instead of just url cleared from slashes.

node: Support newer electron/get

---

node/README.md
node/flatpak-node-generator.py

This is needed in cases when native modules wirh node (not electron) ABI are required at build time (e.g. for node-sass) and setting `npm_config_nodedir` isn't enough.
Here we just symlink `/usr/lib/sdk/nodeN/include` to `flatpak-node/cache/node-gyp/VERSION/include`. Such script could be added manually, but I believe it would be more convinient if the generator handles it.

node: Add option to symlink SDK node headers

---

pip/flatpak-pip-generator

The reasonable default in pip that supports build isolation is to disable it. Fixes #157

Reverse build isolation switch

---

pip/flatpak-pip-generator

better to have some logs than a spin wheel that doesn't even work on flathub build system.
I also had the impression that it slightly improves build time, but I don't have any number to support this.

pip: add verbose flag to install command

---

cpan/flatpak-cpan-generator.pl

cpanminus may output information about up/downgrading of modules it
installs, e.g.:
Successfully installed PathTools-3.75 (upgraded from 3.74)
Correct the regular expression matching the installed packages so only
the name is matched.

cpan: Correct parsing of output from cpanminus

---

node/flatpak-node-generator.py

In some cases apps have different components/modules in the same
repository, and thus the flatpak for them would need several generated
node sources. However, if we try to use both generated sources in the
same flatpak module, they'd fail because we'd try to create directories
(index-v5 and hash-prefixes) that may exist.
Thus, in order to support using multiple generated sources, this patch
makes the generated sources be tolerant to the existence of the
mentioned folders.

node: Support having multiple generated sources

---

dotnet/flatpak-dotnet-generator.py

- enable.sh was removed in the dotnet5 extension.

dotnet: Set PATH without enable.sh

---

node/flatpak-node-generator.py

Since v2 is backwards compatible with v1, this seems to be all that's
needed to support lockfile v2.
Closes: #192

node: Support lockfile v2

---

cpan/flatpak-cpan-generator.pl

Recent versions of flatpak-builder will reject this, causing build failures.

cpan: Don't put slashes in dest-filename

---

cargo/flatpak-cargo-generator.py

Look into dependencies in cargo git packages and load all in-tree dependencies (the ones that have `path` property).
Fixes #181
Fixes #212
Closes #200

cargo: Load in-tree dependencies from git packages

---

pip/flatpak-pip-generator

Use os.path.basename() to strip out the path component of tempdir prefix and output filename, when it's derived from the requirements file name.
Fixes #220.

pip: Allow path in --requirements-file argument

---

node/README.md
node/flatpak-node-generator.py

NW.js itself isn't stored in the lockfile (as far as I can tell), thus trigger NW.js source addition if the lockfile has `nw-builder` package - the most commonly used one to build NW.js apps.
I don't know a generic way to determine used NW.js version from well-known files, thus the NW.js version has to be passed on CLI via the new `--nw-version` option.
Unlike `electron/get`, `nw-builder` download cache can be stored anywhere (by default in the `cache/` subdir of the project), thus we download it to `flatpak-node/nwjs-cache/` dir, which should be symlinked manually to a proper path.
node-headers and 3rd-party ffmpeg are added for completeness, I'm not sure if these are useful in real projects.

node: Add NW.js support

---

node/flatpak-node-generator.py

- Dugite has at least one fork used in the wild, so we should handle it as well as the original package.
- Since GitHub repo may not have the tags matching given package version, pull package contents from a CDN instead of git repo

node: Update dugite special source support

---

node/flatpak-node-generator.py

in python 3.10rc1 a deprecation warning is given for `asyncio.get_event_loop()` since there is no current event loop. instead a better way of starting a async block from synchronous code is to use `asyncio.run(function(args))`

remove depricated asyncio call

---

cargo/flatpak-cargo-generator.py

Store loaded git repos in a special variable and pass it to package handler function, so that each repo is loaded only once.
Upon generating flatpak-builder sources, create git repo checkouts first, then, for each git package, copy subdir from checkout.
This should avoid unnecessary IO and make the generator behavior closer to what `cargo vendor` does.

cargo: Separate git repos from git packages

---

node/flatpak-node-generator.py

```python
>>> import urllib.parse
>>> original_url = urllib.parse.urlparse("git+ssh://git@github.com/bengotow/slate-edit-list.git#b868e1088b44ad1adb2cb06bbbb847a2fef7edb5")
>>> original=original_url.geturl()
>>> commit=original_url.fragment
>>> original
'git+ssh://git@github.com/bengotow/slate-edit-list.git#b868e1088b44ad1adb2cb06bbbb847a2fef7edb5'
>>> original_version = f'{original}#{commit}'
>>> original_version
'git+ssh://git@github.com/bengotow/slate-edit-list.git#b868e1088b44ad1adb2cb06bbbb847a2fef7edb5#b868e1088b44ad1adb2cb06bbbb847a2fef7edb5'
```
`f'{source.original}#{source.commit}'` is wrong.

node: Fix npm git patch url match

---

node/flatpak-node-generator.py

Versions >=1.16.0 have changed `browsers.json` path in the repo.

node: Update playwright support

---

node/README.md
node/flatpak-node-generator.py

Use the recently-added `inline` type source to embed arbitrary data instead of (ab)using `script` type source to generate a python script. This way it's a bit faster, makes generated sources file a bit smaller, and makes the flatpak-node-generator code much simpler.

node: Use inline type source to embed data

---

node/flatpak-node-generator.py

The problem:
`.yarnrc` / `.npmrc` can define custom node.js target, so that native node modules will build against it. But since we only read lock files, there is no way for us to determine which node-headers versions are required in this case.
The proposed solution:
Read rcfiles as well, and generate sources based on their content.
I'm not sure if I took the right approach to fit in nicely to the code structure, so if not - I hope @refi64 will point me to the right direction.
This adds several new abstractions:
- `NodeHeaders` - the node version item, similar to `Package`
- `NodeHeadersProvider` - implements generation of flatpak-builder source entries based on given `NodeHeaders`
- `YarnRCFileProvider` - `.yarnrc` file parser, extracts `NodeHeaders` items

node: Implement rc-file source provider

---

go-get/flatpak-go-vendor-generator.py

It appears that some files can have only one hyphen, e.g.
With this commit the version in the line is taken as is wheras before it
would have been tried to parse it into a date.
I've cooked up this patch in order to be able to build syncthing: https://github.com/flathub/me.kozec.syncthingtk/pull/44

go-vendor: handle lines with no date

---

go-get/README.md

The examples of how to use the Flatpak Go Get Generator is currently slightly outdated.
This PR adds a second example Manifest which:
* Is written in YAML
* Shows a whole example manifest file
* Configures the GO111MODULE

[doc] Add second example to go-get readme

---

pip/flatpak-pip-generator

The new YAML flags allows writing the output as YAML instead of JSON.

Add --yaml flag to flatpak-pip-generator

---

pip/flatpak-pip-generator

PyQt is widely used, but it is not supported by flatpak-pip-generator. There is now a [BaseApp for PyQt](https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp) for PyQt available. Instead of failing and leaving the User alone, flatpak-pip-generator will now provide a Link to the new BaseApp.
I know, that flatpak-pip-generator can also be used for other Repos than Flathub, but I think most of the Users are using it for Flathub. The others can go the the linked repo and copy the build files.

pip: Add Message for PyQt BaseApp

---

node/flatpak-node-generator.py

Electron version in `.yarnrc`/`.npmrc` may be different from the version in lockfile. In such case, if the version from rcfile is used for packaging, build will fail, since we only have the headers, but not the binaries for matching version.
Such case was observed with VSCode; despite it seems like a human error that is fixed by now, I believe `flatpak-node-generator` should be able to handle it.
This patch adds a cli option that tells the generator to download electron binaries for each electron version discovered in rcfiles.

node: Option to get electron binaries per headers

---

cpan/flatpak-cpan-generator.pl

Regression was introduced by ba5005689bac0f5bcfc8a9531da3c576260ceef2
Without escaping $ character I'm getting the following error:
> Global symbol "$FLATPAK_DEST" requires explicit package name (did you forget to declare "my $FLATPAK_DEST"?) at /app/bin/flatpak-cpan-generator.pl line 125.
> Global symbol "$FLATPAK_DEST" requires explicit package name (did you forget to declare "my $FLATPAK_DEST"?) at /app/bin/flatpak-cpan-generator.pl line 125.
> Bareword "main" not allowed while "strict subs" in use at /app/bin/flatpak-cpan-generator.pl line 140.
> Execution of /app/bin/flatpak-cpan-generator.pl aborted due to compilation errors.

cpan: Fix ba500568 regression, escape $ character

---

node/flatpak-node-generator.py

From Electron release page, it can be seen that v19 and v20 drop the linux-ia32 supports:
https://github.com/electron/electron/releases
This commit skips linux-ia32 for Electron v19+.

* Fix support for Electron v19+.

---

dotnet/flatpak-dotnet-generator.py

At the moment, the sources generated by flatpak-dotnet-generator appear in an undefined order. This appears to be different each time I run the command, which means if I commit a generated sources file to a repository, it is difficult to keep track of changes that occur and commits end up being much larger than necessary. We can solve that by sorting the list of sources. Ordering by `dest-filename` seems like a reasonable scheme to me.

dotnet: Sort sources to avoid needless changes

---

node/README.md

I had to dig in the source code to find out that the path is different when `--xdg-layout` is set.

flatpak-node-generator README: Mention XDG path of electron node headers

---

node/flatpak_node_generator/package.py
node/flatpak_node_generator/providers/npm.py
node/flatpak_node_generator/providers/yarn.py
node/tests/data/packages/missing-resolved-npm/package-lock.v2.json
node/tests/data/packages/missing-resolved-npm/package.json
node/tests/test_providers.py

We don't use the `resolved` value anywhere in the npm codepath, so it seems safe to make the field optional.
Renamed `ResolvedSource` to `RegistrySource` because objects of the former class without an actual `resolved` value don't feel right.
Fixes #295
Supersedes #241

node: Allow empty `resolved` field in lockfiles

---

pip/flatpak-pip-generator

This PR adds a comment to the YAML output of flatpak-pip-generator, that shows what command was used to create the file.

pip: Add comment to YAML output

---

node/flatpak_node_generator/package.py
node/flatpak_node_generator/providers/npm.py
node/tests/data/packages/url-as-dep/package-lock.v1.json
node/tests/data/packages/url-as-dep/package-lock.v2.json
node/tests/data/packages/url-as-dep/package.json
node/tests/test_providers.py

"[URL as dependency](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#urls-as-dependencies)" is the term used by NPM documentation; in fact, it refers to direct package URLs in the `version` field.
Should fix #145, and probably fix #301

node: Support url as dependency

---

go-get/flatpak-go-vendor-generator.py

The generator did not like this line which I encountered for syncthing 1.5.0:
"# github.com/spaolacci/murmur3 v1.1.0 => github.com/twmb/murmur3 v1.1.3"
This change makes it work sufficiently well. That is, flatpak-builder
builds it fine, so I guess the dependencies were correct enough for
the build system.

go: support "=>" lines by splitting the line from the back

---

pip/flatpak-pip-generator

Fixes: https://github.com/flatpak/flatpak-builder-tools/issues/319

pip: Sort generated dependencies by name

---

cargo/flatpak-cargo-generator.py

Enables [shallow clone](https://www.git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) to reduce download size.

cargo: Enable shallow git clone

---

node/flatpak_node_generator/providers/special.py

Use the NPM registry to get metadata instead of downloading the packages ourselves, and support esbuild versions with scoped package names.
Fixes #334

node: Improve esbuild special source support

---

cargo/flatpak-cargo-generator.py

If for some reason workspace is empty, root_toml['workspace'] is {}, which was raising a KeyError.
This was triggered by librespot:
https://github.com/librespot-org/librespot/blob/dev/Cargo.toml#L13

cargo: fix crash if workspace is empty

---

.github/workflows/node.yaml
node/flatpak_node_generator/providers/npm.py
node/tests/conftest.py
node/tests/data/packages/electron/package-lock.v3.json
node/tests/data/packages/local/package-lock.v3.json
node/tests/data/packages/minimal-git/package-lock.v3.json
node/tests/data/packages/missing-resolved-npm/package-lock.v3.json
node/tests/data/packages/url-as-dep/package-lock.v3.json
node/tests/test_providers.py
node/tools/lockfile-utils.sh

There are 2 kinds of NPM lockfile syntaxes with major differences: modern, stored in `packages` NPM lockfile property, and legacy, stored in `dependencies`. I'm calling them `v2` and `v1`, respectively. Lockfiles version 1 contains only `v1`, version 2 contains both, and the recent version 3 contains only `v2`.
The `v2` syntax seems concise and overall more sane than `v1`. It's non-recursive, `version` field contains just the version, and, to my understanding the package origin is determined based on the URI scheme in the `resolved` field. However, the `v2` syntax doesn't seem provide package name information (the `name` field is optional and not present for most dependencies).
I didn't yet figure out how to adapt the git-source-patching code for `v2` syntax, thus git sources and …

node: Add initial lockfile v3 support

---

cargo/flatpak-cargo-generator.py

Cargo with `inherit-workspace` feature requires workspace packages Cargo.toml's to be resolved when using vendored sources, because the workspace manifest won't be available when building them.
Fixes #348 
See also https://github.com/rust-lang/cargo/pull/11414

cargo: Embed resolved manifest in generated sources

---

pip/flatpak-pip-generator
pip/readme.md

If pip fails to download, the generated sources file is empty and, arguably, useless. Instead of silently generating an empty file, the error is propagated now.
The root cause appears to be a bug in pip.
https://github.com/flatpak/flatpak-builder-tools/issues/265

pip: propagate error when downloading packages

---

pip/flatpak-pip-generator

Fixes: https://github.com/flatpak/flatpak-builder-tools/issues/362
one additional changes is it uses only filename for the tmpfiles, since when directory contains `../` it makes a mess.

pip: differenciate between package, path and filename properly

---

pip/flatpak-pip-generator

See commit message for explanation.
This is useful when someone wants to ignore a problematic package specified in `requirements.txt`. It can be due to multiple reasons that comes to mind: 
- the package is not available for current python version as a result downloading errors out even if other packages in the list are fine eg.
```
dataclasses==0.8
Sample2
```
- The package doesn't have a sdist tarball on pypi, and we want to manually add it to the manifest to build from source. Eg.
```
pyside6
Sample2
```
- Bugs like https://github.com/flatpak/flatpak-builder-tools/issues/328, that prevents producing a manifest altogether
(alternate take on https://github.com/flatpak/flatpak-builder-tools/pull/217, but a bit complicated)
Usage:
```
./flatpak-pip-generator --ignore-pkg <pkg1> <pkg2> -r …
```

Allow ignoring package in flatpak-pip-generator

---

.github/workflows/node.yaml

This PR bumps the `actions/checkout` version from v3 (Node 16) to v4 (Node 20) as Node 16 is reaching eol soon.
Ref. https://nodejs.org/en/blog/announcements/nodejs16-eol

CI: bump actions/checkout to v4

---

spm/README.md
spm/flatpak-spm-generator.swift
spm/quickstart/Package.swift
spm/quickstart/Sources/quickstart/main.swift
spm/quickstart/com.flatpak.quickstart.json
spm/quickstart/org.flatpak.quickstart.json

Hi!
This PR adds support for [SPM](https://www.swift.org/documentation/package-manager/) (e.g. useful in combination with the [Swift 5 SDK Extension](https://github.com/flathub/flathub/pull/4935)). It contains a script for generating the necessary  files, a README and a sample Swift package.

Add Swift Package Manager (SPM) support

---

poetry/flatpak-poetry-generator.py

Directory sources, or "path dependencies" as the Poetry documentation[1] calls them, are by definition not available on PyPi. As such, there is no point in attempting to download these since there is no way to tell where the source could be acquired from the lockfile alone.
[1]: https://python-poetry.org/docs/dependency-specification/#path-dependencies

Skip directory sources in Poetry lockfiles

---

spm/flatpak-spm-generator.swift

spm: Add the script to the generate json
Create the folders in the setup script.
The rationale is to only have to add `generated-sources.json` to the manifest, so we need to list the `setup-offline.sh` too.
The `setup-offline.sh` need to create the destination directories otherwise it fails.
spm: Fix the generation when a package name is the substring of another
Example: `SwiftPangoCairo` and `SwiftPango`. The latter would be skipped.
(trying to build https://github.com/flathub/co.luoja.Telyn from source)

spm: Fixes

---

cargo/flatpak-cargo-generator.py

Current implementation assumes all workspace dependencies in workspace crates are single entry maps of
`<dep>.workspace = true` and overrides the `<dep>` value from the workspace
This fails if the workspace crate includes other keys for the `<dep>`, such as `optional = true` or
`features = []`, since those are dropped.
The current implementation also failed to properly recurse to capture `target.cfg(..).dependencies`.
This has been updated to properly fix the above
This fix was used to successfully generate sources for and build https://github.com/flathub/org.squidowl.halloy/pull/5

Fix cargo workspace replacement for git deps

---

cargo/flatpak-cargo-generator.py

Fixes a crash when git dependencies are in a workspace that declares no workspace-level dependencies. [For example](https://github.com/warp-tech/russh/blob/1d7dab8db178455bc0d3ce1be8faeebc978e45d3/Cargo.toml#L1-L2):
```toml
package.name = "uses-russh"
dependencies.russh.git = "https://github.com/warp-tech/russh"
```
`cargo generate-lockfile && flatpak-cargo-generator.py Cargo.lock`:
```
INFO:root:Loading packages from https://github.com/warp-tech/russh
INFO:root:Adding package russh from https://github.com/warp-tech/russh
INFO:root:Adding package russh-cryptovec from https://github.com/warp-tech/russh
INFO:root:Adding package russh-keys from https://github.com/warp-tech/russh
Traceback (most recent call last):
File "/tmp/flatpak-builder-tools/cargo/flatpak-cargo-generator.py", line 470, …
```

Fix KeyError when cargo git deps omit workspace.dependencies

---

node/flatpak_node_generator/electron.py
node/flatpak_node_generator/providers/special.py
node/tests/data/packages/electron/package-lock.v1.json
node/tests/data/packages/electron/package-lock.v2.json
node/tests/data/packages/electron/package-lock.v3.json
node/tests/data/packages/electron/package.json
node/tests/data/packages/electron/yarn.lock
node/tests/test_providers.py

This also updates the existing electron test & extends it to test this out.
Fixes #370.

node: Create integrity file symlink for new electron/get versions

---

cargo/flatpak-cargo-generator.py

Right now, `get_git_repo_packages` only finds git dependencies that are:
- their repo's root crate (`Cargo.toml` or `*/Cargo.toml`)
- in the dependency or workspace member trees of those root crates
Otherwise, `get_git_package_sources` throws a KeyError.
I found this with `eframe`:
```toml
package.name = "uses-eframe"
dependencies.eframe.git = "https://github.com/emilk/egui"
```
```sh
cargo generate-lockfile # succeeds
flatpak-cargo-generator.py Cargo.lock -d # KeyError: 'eframe'
```
<details>
<summary>Full Debug Log</summary>
<pre>
<code>
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:depends-on-eframe has no source
INFO:root:Loading packages from https://github.com/emilk/egui
DEBUG:root:Loading workspace member ./crates/ecolor/Cargo.toml in …

Find all crates in git repositories, matching cargo's behavior

---

cargo/flatpak-cargo-generator.py

Various errors I encountered while trying the script and then to build a Flatpak app.
See each commit message for details.
See the last commit of https://github.com/flathub/org.gnome.Fractal/pull/41 for the differences in the generated sources.

Fixes to flatpak-cargo-generator

---

CODEOWNERS
gradle/README.md
gradle/flatpak-gradle-generator.py

I don't know what I'm doing, but I can parse the logs of a Gradle build and generate a `json` file to build Ghidra.

Add Gradle generator

---

cargo/README.md
cargo/pyproject.toml

I like to give tools such as `flatpak-cargo-generator.py` a dedicated virtualenv with the necessary dependencies, and Poetry was an easy way to handle the logistics behind the scenes.

Simplify flatpak-cargo-generator.py dependency install with Poetry

---

dotnet/flatpak-dotnet-generator.py

When doing so, `dotnet restore` gets executed once for each runtime, creating a file that contains all the required sources.

dotnet: allow specifying the --runtime argument multiple times

---

pip/flatpak-pip-generator

pypi enforces case-insensitive naming https://peps.python.org/pep-0508/#names however we cannot say the same for vcs packages.
Fixes https://github.com/flatpak/flatpak-builder-tools/issues/428

pip: Ignore case and assume lowercase name when package is from pypi

---

node/README.md

When the `node_modules` directory is present, the `generated-sources.json` file will (most likely) be missing dependencies.
- Fixes #377
- Fixes #409
- Fixes #426
Discovered the solution in https://github.com/flatpak/flatpak-builder-tools/issues/354#issuecomment-1478518442 ... figured an update to the documentation would be worthwhile.

docs(node): add clarifiaction around `node_modules` directory

---

dotnet/flatpak-dotnet-generator.py

This expands on https://github.com/flatpak/flatpak-builder-tools/pull/206 by running `dotnet restore` operations for multiple csproj files in parallel. 
This can greatly speed up the processing time for larger dotnet projects.
Let me know if you'd like any changes :smile:

dotnet: Process multiple projects in parallel

---

cargo/README.md
cargo/quickstart/com.flatpak.quickstart.json

Hi !
This commit fixes 2 things in the flatpak manifest:
* In the `build-commands`, cargo build the app with `--release`. But the folder referenced is `/debug/` instead of `/release/`
* In the file `com.flatpak.quickstart.json`, there is a small typo: `qucikstart` instead of `quickstart`

Fix some typos in the cargo flatpak manifest

---

pip/flatpak-pip-generator

If the file is of type none-any.whl it can be used as well, because it is suitable for all architectures
Files: flatpak-pip-generator

Add none-any.whl

---

node/flatpak_node_generator/providers/npm.py

_(Please correct me if I'm wrong)_
The conditions here, if I understand correctly, are to detect whether a package is from a local source, with these two clues:
- none of its parent directories (up to the lockfile) is called `node_modules`, and
- it has a `package.json`
The first one, however, has two issues:
- `Path.parents` yields `PosixPath` objects, not strings, so the test `'node_modules' in ...` never succeeds.
- `Path.parents` yields all logical ancestors of a path (see https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parents), which is probably not what we want here.
This change fixes these issues.
I tested this by running `flatpak-node-generator -r npm package-lock.json` under [Insomnia](https://github.com/Kong/insomnia) source tree.
- Before, it only emits about …

node: Fix path-based local package detection

---

node/README.md

we don't have to clone the repo just to install the package, cf. https://pip.pypa.io/en/stable/topics/vcs-support/#url-fragments

docs: Tweak pipx install cmd

---

pip/flatpak-pip-generator

The freedesktop runtime only provides python3, so this will incorrectly skip important packages when run in python2 mode that are actually needed.

pip: don't consider system_packages for python2

---

pip/flatpak-pip-generator
pip/readme.md

This PR adds support for reading [dependencies from a ypproject.toml](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata). On Python versions older than 3.11, you need to install tomli to use this feature.

pip: Add support for pyproject.toml

---

deno/src/utils.ts
deno/tests/utils.test.ts

Ensure the original file extension is preserved when hashing filenames

Fix shortHash extension handling

---

cargo/flatpak-cargo-generator.py

Fixes https://github.com/flatpak/flatpak-builder-tools/issues/414

cargo: Use force checkout if git sources in cache differ

---

cargo/README.md

Without this step the configuration file is at the wrong place, and cargo won't use the vendored sources.

Setup cargo config in cargo generator README

---

pip/flatpak-pip-generator.py

Currently, when generating source files for Python modules using JSON, the file does not end with a newline.
According to [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206), this should not be the case.
Additionally, manually editing the files afterward will most likely add a newline, thereby cluttering the Git diffs.

Add end-of-file newline for flatpak-pip-generator

---

deno/deno.json
deno/src/main.ts
deno/tests/main.test.ts

Deno: Inline required fields from meta.json

---

gradle/README.md

Some time ago, I developed a [Gradle plugin](https://plugins.gradle.org/plugin/io.github.jwharm.flatpak-gradle-generator) that generates a flatpak sources file. I hope it will be easier to use than the existing script. This PR adds a link and description of the plugin to `gradle/README.md`, with the script as an alternative option.

Add link and documentation for Gradle plugin

---

cargo/flatpak-cargo-generator.py

this was generating invalid hashes because tomlkit.load and tomlkit.parse return TomlDocument instead of dict.

flatpak-cargo-builder: unwrap tomldoc
