flatpak/flatpak-builder-tools

- pip/flatpak-pip-generator
Here's one bugfix and two options that I found useful.
> More options

- npm/flatpak-npm-generator.py
> npm3 uses a different cache structure

- npm/flatpak-npm-generator.py
npm has support to pull modules directly from git repo. This pr adds support to create modules for such modules. It also generates a patch script to patch the package-lock.json and package.json, so as to use these local copies.
> Npm git module generation

- yarn/flatpak-yarn-generator.py
As in https://github.com/Microsoft/vscode
> Removing duplicates due to recursive directories

- rubygems/LICENSE
- rubygems/README.md
- rubygems/flatpak_rubygems_generator.rb
This script may help people who want to distribute Ruby applications as Flatpak.
> Add Rubygems module generator script for Ruby applications

- npm/flatpak-npm-generator.py
See also:
https://github.com/flatpak/flatpak-builder-tools/issues/40#issuecomment-447070874
> flatpak-npm-generator.py: Fix for electron for arm. Closes #40

- yarn/flatpak-yarn-generator.py
Just to avoid [these](https://github.com/flathub/io.github.liberodark.OpenDrive/blob/master/bootstrap.sh#L15) sort of stuff :wink:
Closes #57.
> Rectify/Update Electron to Flatpak arches

- pip/flatpak-pip-generator
- pip/readme.md
You can now use the script in two different ways
```shell
flatpak-pip-generator pyotp
```
which will generate 
```json
[
{
"name": "python3-pyotp",
"buildsystem": "simple",
"build-commands": [
"pip3 install --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} pyotp"
],
"sources": [
{
"type": "file",
"url": "https://files.pythonhosted.org/packages/b1/ab/477cda97b6ca7baced5106471cb1ac1fe698d1b035983b9f8ee3422989eb/pyotp-2.2.7.tar.gz",
"sha256": "be0ffeabddaa5ee53e7204e7740da842d070cf69168247a3d0c08541b84de602"
}
]
}
]
```
We can now pass a requirements.txt path to be parsed for pip dependencies. 
```shell
flatpak-pip-generator --requirements-file=./Authenticator/requirements.txt --output authenticator
```
which will generate all the python dependencies required on the file. …
> pip: add requirements file support

- cargo/flatpak-cargo-generator.py
Cargo expects the git repository to live in a certain directory.
That directory has the hash of the URL as a suffix, cf.
https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/git/source.rs#L72
and
https://github.com/rust-lang/cargo/blob/d5d7557cf5ba2993cab572076753db73091a5b7f/src/cargo/sources/git/source.rs#L118.
It uses siphash
https://github.com/rust-lang/cargo/blob/d5d7557cf5ba2993cab572076753db73091a5b7f/src/cargo/sources/git/source.rs#L12
and a 0xff suffix is important, cf. impl Hash for str, e.g.
https://doc.rust-lang.org/src/core/hash/mod.rs.html#611-616
> cargo: generate source entries for git sources

- node/flatpak-node-generator.py
- node/webpack-quick-start/generated-sources.json
Fixes #79, @muelli mind taking this for a spin?
> node: Revamp npm resolved sources and improve cached registry queries

- cargo/flatpak-cargo-generator.py
With this change, the script behaves a bit more like "cargo vendor".
That was the intention of the script with "normal", i.e. crates.io
dependencies. cargo vendor places git dependencies in the same folder
and produces a .cargo-checksum.json file.  We try to do it similarly.
I needed to patch the cargo generator to build a flatpak for deltachat: https://github.com/flathub/chat.delta.desktop/pull/25
I'll be more than happy if these changes won't be required or if someone makes it work more properly.
> cargo: vendorise git dependencies

- node/README.md
- node/flatpak-node-generator.py
Fixes #104
@refi64 Sorry for rushing this, if you're in progress of implementing this yourself - feel free to close this PR.
> node: Add support for electron node-headers

- cargo/flatpak-cargo-generator.py
- Put git fetching into separate functhion
- Always check if chached repo is on correct commit
- Fetch cached repo if commit changed
> Cargo: minor fixes and improvements

- pip/flatpak-pip-generator
> Don't crash on Pip VCS requirements with no name

- cargo/flatpak-cargo-generator.py
> Cargo: Support wildcards in workspace

- node/flatpak-node-generator.py
- Now download filename depends on browser revision
- Since newer versions write a special file after download completes, and check its presence
> node: Support newer playwright versions

- node/flatpak-node-generator.py
Adopted [this](https://github.com/yarnpkg/yarn/blob/a4708b29ac74df97bac45365cba4f1d62537ceb7/src/resolvers/exotics/git-resolver.js#L31-L46) function from Yarn code to determine if resolved source points to a git repo.
Fixes #185
> node: Copy git detection method from Yarn itself

- node/flatpak-node-generator.py
`esbuild` package has its native binaries in another npm packages, like `esbuild-linux-64`. The binary package is installed from `esbuild` post-install script and doesn't get into lockfile. Luckily, `esbuild` supports downloading package directly without using `npm` - we could use that.
Although I wonder if there is a way to somehow add to cache a package not listed in lockfiles - probably this could've been a better approach.
> node: Handle esbuild special source

- go-get/flatpak-go-vendor-generator.py
This patch adds some more replacements for known go modules' URLs.
> go-get: Add more known module URL replacements

- node/flatpak-node-generator.py
- Download newer chromium revisions from MS CDN
- Skip browsers not installed by default
- Raise exception on unknown browser
> node: Update playwright special source handler

- node/flatpak-node-generator.py
In short:
- Reformatting
- Type annotation fixes
- Fixes packages sometimes not working when there's a slash in the name
- Fixes ENOTCACHED errors when there's `/../` anywhere in the package's metadata
> Various minor Node fixes

- pip/flatpak-pip-generator
- this should fix some problems with source building when it's not necessary
- this partially revert f732068a39b2cbc662dbd271003a7ef87f9d498f
@Lctrs you did that patch originall, @TingPing you did merge it. 
Closes #226
> Keep using 'any' wheels

- pip/flatpak-pip-generator
Now you can run the script with --requirements-file=~/foo/requirements.txt.
> pip: expanduser on the requirements file argument

- cpan/flatpak-cpan-generator.pl
Closes https://github.com/flatpak/flatpak-builder-tools/issues/273
> Fixed prefix and destination directory for CPAN

- cargo/flatpak-cargo-generator.py
Some git repositories listed in Cargo.lock can have their Cargo.toml in a subdirectory instead of the root directory.
With this change, subdirectories get scanned for Cargo.toml as well, if it isn't found in the repository root.
I tested the change with a few Cargo.lock files and the output is the same for files that already worked before.
Fixes #279
> cargo: Find Cargo.toml in repo subdirectories

- pip/flatpak-pip-generator
This should avoid confusion like in #302.
> pip: Show message if package is in system_packages

- node/flatpak_node_generator/providers/yarn.py
This is a bit of refactoring. The idea is to separate yarn.lock reading into two phases: 1. parsing into a (json-like) structure and 2. loading the structure into python objects.
I believe this makes the code more compact and easier to follow, and hopefully will make adding lockfile v2 support less invasive.
> node: Decouple yarn.lock parsing from loading

- node/flatpak_node_generator/providers/npm.py
> node: Skip local source check in node_modules dir

- node/flatpak_node_generator/providers/npm.py
This is a rather quick-and-dirty implementation. We probably can implement custom registries in a nicer way, but at least this does the job.
Fixes #316
> node: Support custom registries

- cargo/flatpak-cargo-generator.py
Adds support for multiple subdirectories with `Cargo.toml` per git repository,
Re-implementation of #281, more generic fix for #279
> cargo: Support multiple project subdirs

- dub/flatpak-dub-generator.py
> dub: Generate local-packages.json as inline source and other small fixes

- cargo/flatpak-cargo-generator.py
> cargo: Initialize git submodules when fetching repo

- node/flatpak_node_generator/providers/special.py
> update fallback firefox version to one that actually exists

- pip/flatpak-pip-generator.py
Fixed duplication of file extension and added the ability to specify a directory for output
> pip: Improve output filename handling
